# Generated by Django 4.1.5 on 2023-02-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="")),
                ("qualification", models.TextField(default="")),
                ("number", models.TextField(default="")),
                ("image", models.TextField(default="")),
                ("country", models.TextField(default="")),
                ("workspace", models.TextField(default="")),
                ("first_time_mon", models.TimeField(blank=True, null=True)),
                ("second_time_mon", models.TimeField(blank=True, null=True)),
                ("third_time_mon", models.TimeField(blank=True, null=True)),
                ("first_time_tue", models.TimeField(blank=True, null=True)),
                ("second_time_tue", models.TimeField(blank=True, null=True)),
                ("third_time_tue", models.TimeField(blank=True, null=True)),
                ("first_time_wed", models.TimeField(blank=True, null=True)),
                ("second_time_wed", models.TimeField(blank=True, null=True)),
                ("third_time_wed", models.TimeField(blank=True, null=True)),
                ("first_time_thur", models.TimeField(blank=True, null=True)),
                ("second_time_thur", models.TimeField(blank=True, null=True)),
                ("third_time_thur", models.TimeField(blank=True, null=True)),
                ("first_time_fri", models.TimeField(blank=True, null=True)),
                ("second_time_fri", models.TimeField(blank=True, null=True)),
                ("third_time_fri", models.TimeField(blank=True, null=True)),
                ("first_time_sat", models.TimeField(blank=True, null=True)),
                ("second_time_sat", models.TimeField(blank=True, null=True)),
                ("third_time_sat", models.TimeField(blank=True, null=True)),
                ("first_time_sun", models.TimeField(blank=True, null=True)),
                ("second_time_sun", models.TimeField(blank=True, null=True)),
                ("third_time_sun", models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="visitor_count",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("v_count", models.IntegerField(default=0)),
            ],
        ),
    ]
