# Generated by Django 4.1.5 on 2023-02-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="apply_as_doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TimeField(default="")),
                ("qualification", models.TimeField(default="")),
                ("city", models.TimeField(default="")),
                ("country", models.TimeField(default="")),
                ("number", models.TimeField(default="")),
                ("email", models.TimeField(default="")),
            ],
        ),
    ]
