# Generated by Django 4.1.5 on 2023-02-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0002_apply_as_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apply_as_doctor",
            name="city",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="apply_as_doctor",
            name="country",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="apply_as_doctor",
            name="email",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="apply_as_doctor",
            name="name",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="apply_as_doctor",
            name="number",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="apply_as_doctor",
            name="qualification",
            field=models.TextField(default=""),
        ),
    ]
