# Generated by Django 4.1.5 on 2023-03-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0003_alter_apply_as_doctor_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply_as_doctor",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
