# Generated by Django 4.1.5 on 2023-01-22 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="")),
                ("email", models.TextField(default="")),
                ("subject", models.TextField(default="")),
                ("description", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="profile_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.TextField(default="")),
                ("l_name", models.TextField(default="")),
                ("city", models.TextField(default="")),
                ("country", models.TextField(default="")),
                ("gender", models.TextField(default="")),
                ("address", models.TextField(default="")),
                ("dob", models.DateField(blank=True, null=True)),
                ("province", models.TextField(default="")),
                ("image", models.TextField(default="")),
                ("education", models.TextField(default="")),
                ("marital_status", models.TextField(default="")),
                ("profession", models.TextField(default="")),
                ("age", models.IntegerField(default=0)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
