# Generated by Django 4.1.5 on 2023-01-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile_data",
            old_name="user_id",
            new_name="user",
        ),
    ]
