# Generated by Django 4.1.5 on 2023-01-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0002_rename_user_id_profile_data_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile_data",
            old_name="user",
            new_name="CustomUser",
        ),
    ]
