# Generated by Django 4.1.5 on 2023-02-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0003_rename_user_profile_data_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile_data",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
