# Generated by Django 4.1.5 on 2023-02-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0001_initial"),
        ("chatbot_app", "0004_profile_data_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_mon_first", models.BooleanField(default=0)),
                ("status_mon_second", models.BooleanField(default=0)),
                ("status_mon_third", models.BooleanField(default=0)),
                ("status_tue_first", models.BooleanField(default=0)),
                ("status_tue_second", models.BooleanField(default=0)),
                ("status_tue_third", models.BooleanField(default=0)),
                ("status_wed_first", models.BooleanField(default=0)),
                ("status_wed_second", models.BooleanField(default=0)),
                ("status_wed_third", models.BooleanField(default=0)),
                ("status_thur_first", models.BooleanField(default=0)),
                ("status_thur_second", models.BooleanField(default=0)),
                ("status_thur_third", models.BooleanField(default=0)),
                ("status_fri_first", models.BooleanField(default=0)),
                ("status_fri_second", models.BooleanField(default=0)),
                ("status_fri_third", models.BooleanField(default=0)),
                ("status_sat_first", models.BooleanField(default=0)),
                ("status_sat_second", models.BooleanField(default=0)),
                ("status_sat_third", models.BooleanField(default=0)),
                ("status_sun_first", models.BooleanField(default=0)),
                ("status_sun_second", models.BooleanField(default=0)),
                ("status_sun_third", models.BooleanField(default=0)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_dashboard.doctor",
                    ),
                ),
            ],
        ),
    ]
