# Generated by Django 4.1.5 on 2023-03-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0003_alter_apply_as_doctor_city_and_more"),
        ("chatbot_app", "0005_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TextField(default="")),
                (
                    "appointment_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot_app.appointment",
                    ),
                ),
                (
                    "doctor_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_dashboard.doctor",
                    ),
                ),
                (
                    "user_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot_app.profile_data",
                    ),
                ),
            ],
        ),
    ]
