# Generated by Django 4.1.5 on 2023-03-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0006_user_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_appointment",
            name="day",
            field=models.TextField(default=""),
        ),
    ]
