# Generated by Django 4.1.5 on 2023-03-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0004_apply_as_doctor_status"),
        ("chatbot_app", "0007_user_appointment_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="doc_timing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.TextField(default="")),
                ("timing", models.DateTimeField(blank=True, null=True)),
                ("status", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_dashboard.doctor",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user_appointment",
            name="appointment_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chatbot_app.doc_timing"
            ),
        ),
        migrations.DeleteModel(
            name="appointment",
        ),
    ]
