# Generated by Django 4.1.7 on 2023-03-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chatbot_app",
            "0008_doc_timing_alter_user_appointment_appointment_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="doc_timing",
            name="timing",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
