# Generated by Django 4.1.7 on 2023-03-14 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0004_apply_as_doctor_status"),
        ("chatbot_app", "0010_user_appointment_date_alter_user_appointment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_appointment",
            name="doctor_details",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="admin_dashboard.doctor"
            ),
        ),
    ]
