# Generated by Django 4.1.7 on 2023-03-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0013_doc_timing_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_appointment",
            name="appointment_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="chatbot_app.doc_timing",
            ),
        ),
    ]
