# Generated by Django 4.1.5 on 2023-03-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0014_alter_user_appointment_appointment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_appointment",
            name="appointment_status",
        ),
        migrations.CreateModel(
            name="timing_exists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot_app.doc_timing",
                    ),
                ),
            ],
        ),
    ]
